### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by embydextrous-zz** [Nescafemix/hintcase#6]
```
    new HintCase(getActivity().getWindow().getDecorView()).show();
```

 I am using this inside fragment. Nothing works. Tried different combos of background and target views.
Am I missing some thing?

**Comment by Nescafemix** [comment]
Hi @embydextrous ,

Thanks for trying the library.

The library has a lot of optional methods to configure the hint, but at least you need to configure 1 HintBlock (.setHintBlock(...) or 1 ExtraBlock (.setExtraBlock(...)) to specify how is the hint that you want to show. I'm going to add some checks in the next version.

You can find some examples of use of the library in the sample application: https://github.com/Nescafemix/hintcase/tree/master/app/src/main/java/com/joanfuentes/hintcaseexample

**Comment by embydextrous-zz** [comment]
I configures a hint block as mentioned in your sample.

```
SimpleHintContentHolder blockInfo =new SimpleHintContentHolder.Builder(fabSellButton.getContext())
                        .setContentTitle("Search")
                        .setContentText("This is an automatic example of a hint over a toolbar item")
                        .setMarginByResourcesId(R.dimen.activity_vertical_margin,
                                R.dimen.activity_horizontal_margin,
                                R.dimen.activity_vertical_margin,
                                R.dimen.activity_horizontal_margin)
                        .build();
        new HintCase(fabSellButton.getRootView())
                .setTarget(fabSellButton, new CircularShape())
                .setShapeAnimators(new RevealCircleShapeAnimator(),
                        new UnrevealCircleShapeAnimator())
                .setHintBlock(blockInfo)
                .show();
```

It is still not working. Are styles mandatory, because I have removed those from your sample code.

**Comment by embydextrous-zz** [comment]
Well I tried your sample app removing styles. It works without styles too. 
Is this a fragment issue?

**Comment by Nescafemix** [comment]
Not really. I suppose that the target view is still not rendered when you launch the hint so it can be showed.

Could you try to launch the hint in the same way that I'm using in the example? (Inside of a Handler waiting some time)

**Comment by embydextrous-zz** [comment]
Ok let me try.
I think it is working but transparent. Because app does not respond to underlying click events for the first time. And it is dismissed on first time and then click listeners work. 
I am trying handler stuff. Will get back to you.

**Comment by embydextrous-zz** [comment]
Handler man. Handler. Awesome. It's working. Thanks.
