### ISSUE TITLE
How to set Target to SlidingTabLayout item or some item in the RecyclerView

### ISSUE THREAD

**Issue by Michinggun** [Nescafemix/hintcase#8]
Hey, your library is awesome. But I need to know how to set target inside SlidingTabLayout item and some item inside the list. Could you provide me an example? I've checking your sample app but I can't found it and I've been trying but it's still not working. Thanks man!

**Comment by Nescafemix** [comment]
Hi @Michinggun ,

You only need to get the targeted view from your layout.
For example, if you want to get the second tab of a TabLayout in a fragment, you could do:

```
TabLayout tabLayout = (TabLayout) fragment.getView().findViewById(R.id.tabs);
View target = null;
if (tabLayout != null) {
    TabLayout.Tab tab = tabLayout.getTabAt(1);
    if (tab != null) {
        target = tab.getCustomView();
    }
}
```

About an item inside a list in a fragment (for example a RecyclerView), you could do:

```
RecyclerView recyclerView = (RecyclerView) fragment.getView().findViewById(R.id.list);
View target = null;
if (recyclerView.getChildCount() > POSITION_ITEM_I_NEED) {
    target = recyclerView.getChildAt(POSITION_ITEM_I_NEED);
}
```

**Comment by Michinggun** [comment]
Hi @Nescafemix ,

Thanks for your reply. I've already tried and it's still not working as I expected.
Here I attached my snippet : 

```
new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                TabLayout tabLayout = ButterKnife.findById(MainActivity.this, R.id.tabs);
                View target = null;
                if (tabLayout != null) {
                    TabLayout.Tab tab = tabLayout.getTabAt(1);
                    if (tab != null) {
                        target = tab.getCustomView();
                        SimpleHintContentHolder blockInfo =
                                new SimpleHintContentHolder.Builder(tabLayout.getContext())
                                        .setContentTitle("Discover")
                                        .setContentText("This is an automatic example of a hint over a toolbar item")
                                        .build();
                        new HintCase(tabLayout.getRootView())
                                .setTarget(target, new CircularShape())
                                .setBackgroundColorByResourceId(R.color.colorGoogle)
                                .setShapeAnimators(new RevealCircleShapeAnimator(),
                                        new UnrevealCircleShapeAnimator())
                                .setHintBlock(blockInfo)
                                .show();
                    }
                }
            }
        }, 2000);
```

Here's the result:
![image](https://cloud.githubusercontent.com/assets/5793036/16157635/900d6444-34e3-11e6-969a-fbe9635c0781.png)

I want to focus on the second tab:
![image](https://cloud.githubusercontent.com/assets/5793036/16157676/b6b656fa-34e3-11e6-8832-9c9c1831f0c1.png)

Is there something wrong that I'm not realized?
Thank you

**Comment by Nescafemix** [comment]
@Michinggun,  Could you try to use the Decorview of the activity instead of the rootview of the tablayout?

```
View view = activity.getWindow().getDecorView();
HintCase hintCase = new HintCase(view)...
```

And could you check if the target is null? If the library receives a null target view, it performs the hint as if target hasn't been added.

Maybe when you launch the hint, the tablayout still doesn't have tabs inflated. Maybe you could move the launch of the hint after you be sure tabs are inflated.

**Comment by Michinggun** [comment]
@Nescafemix, I've found the solution of this problem.
The problem is when you `tab.getCustomView();` it returns null because there isn't any custom view of the tab in the first place.
So, rather than use `tab.getCustomView();`,
it's better to use `((ViewGroup) tabLayout.getChildAt(0)).getChildAt(1);` to get the item view of the tablayout if you're not using the custom view.
And if you wanna use `getCustomView()`, you should use `setCustomView()` first when inflating the tabs.

FYI, Here's the working code:

```
TabLayout tabLayout = ButterKnife.findById(MainActivity.this, R.id.tabs);
                View target = null;
                if (tabLayout != null) {
                    TabLayout.Tab tab = tabLayout.getTabAt(1);
                    if (tab != null) {
                        target = ((ViewGroup) tabLayout.getChildAt(0)).getChildAt(1);
                        SimpleHintContentHolder blockInfo =
                                new SimpleHintContentHolder.Builder(tabLayout.getContext())
                                        .setContentTitle("Discover")
                                        .setContentText("This is an automatic example of a hint over a toolbar item")
                                        .build();
                        View view = getWindow().getDecorView();
                        if (view != null) {
                            new HintCase(view)
                                    .setTarget(target, new CircularShape())
                                    .setBackgroundColorByResourceId(R.color.colorGoogle)
                                    .setShapeAnimators(new RevealCircleShapeAnimator(),
                                            new UnrevealCircleShapeAnimator())
                                    .setHintBlock(blockInfo)
                                    .show();
                        }
                    }
                }
```

Here's the preview:
![screenshot_2016-06-20-14-29-21](https://cloud.githubusercontent.com/assets/5793036/16186260/ada6a9cc-36f3-11e6-9646-7208f66335b9.png)

Hope it will help someone! Thanks for your help! :+1: 
ref: http://stackoverflow.com/questions/33246307/how-do-i-get-the-view-of-a-tab-in-a-tablayout

**Comment by Nescafemix** [comment]
@Michinggun Thanks a lot!
You are right. I was using a custom view, and that is the reason why it was working for me.
I'm glad you found the problem :) and thanks for sharing the solution :)
